version: '3'

services:
  api:
    build: .
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SERVICE_PORT: ${SERVICE_PORT}
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    command: yarn start
    depends_on:
      - postgres

  postgres:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    volumes:
      - pgdata:/pgdata

volumes:
  pgdata:
